AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Go API with SAM

Globals:
  Function:
    Timeout: 30
    Runtime: go1.x
    Architectures:
      - x86_64

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Events:
        GetHello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        PostSubmit:
          Type: Api
          Properties:
            Path: /submit
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ApiFunction.Arn